"""ピンゲージ管理DBの pin_gauge_lending.id に自動採番（IDENTITY）を設定する。

このファイルは .docs/pingauge_management_db 専用です。
既存の Access COUNTER 値は保持し、新規 INSERT 時のみ自動採番します。
PRIMARY KEY が未設定の場合は停止します。
"""

from __future__ import annotations

import argparse
import logging
from pathlib import Path

import psycopg2
from dotenv import dotenv_values

TARGET_DIR = Path(__file__).resolve().parent
ERROR_LOG_FILE = "setup_id_identity_pingauge_management_db.log"
DEFAULT_SCHEMA = "public"
TABLE_NAME = "pin_gauge_lending"
COLUMN_NAME = "id"


def main() -> int:
    args = parse_args()
    setup_logging(TARGET_DIR / ERROR_LOG_FILE)

    try:
        env = load_env(TARGET_DIR / ".env")
        setup_identity(env["DATABASE_URL"], args.schema, dry_run=args.dry_run)
        return 0
    except Exception:
        logging.exception("IDENTITY設定処理が失敗しました")
        return 1


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="pin_gauge_lending.id に自動採番を設定")
    parser.add_argument("--schema", default=DEFAULT_SCHEMA, help="PostgreSQLスキーマ名")
    parser.add_argument("--dry-run", action="store_true", help="検証のみ行い、ALTER TABLEは実行しない")
    return parser.parse_args()


def setup_logging(error_log_path: Path) -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        handlers=[
            logging.FileHandler(error_log_path, mode="w", encoding="utf-8-sig"),
            logging.StreamHandler(),
        ],
    )


def load_env(env_path: Path) -> dict[str, str]:
    values = {key: value for key, value in dotenv_values(env_path).items() if value is not None}
    if not values.get("DATABASE_URL"):
        raise ValueError(".envの必須項目が不足しています: DATABASE_URL")
    return values


def setup_identity(database_url: str, schema: str, *, dry_run: bool) -> None:
    connection = psycopg2.connect(database_url)
    try:
        connection.autocommit = False
        with connection.cursor() as cursor:
            verify_prerequisites(cursor, schema)
            max_id = fetch_max_id(cursor, schema)
            if has_identity(cursor, schema):
                sequence_name = fetch_identity_sequence(cursor, schema)
                next_id = sync_sequence(cursor, sequence_name, max_id, dry_run=dry_run)
                logging.info(
                    "スキップ: %s.%s には既に IDENTITY があります。次の採番値=%s",
                    TABLE_NAME,
                    COLUMN_NAME,
                    next_id,
                )
                if dry_run:
                    logging.info("dry-run: シーケンス同期のみ検証しました")
                else:
                    logging.info("シーケンスを MAX(id)=%s に同期しました", max_id)
            else:
                alter_sql = build_add_identity_sql(schema)
                logging.info("実行予定SQL: %s", alter_sql)
                if dry_run:
                    logging.info(
                        "dry-run: IDENTITY 追加をスキップしました（次の採番値は %s になる想定）",
                        max_id + 1,
                    )
                else:
                    cursor.execute(alter_sql)
                    sequence_name = fetch_identity_sequence(cursor, schema)
                    next_id = sync_sequence(cursor, sequence_name, max_id, dry_run=False)
                    logging.info(
                        "完了: %s.%s に GENERATED BY DEFAULT AS IDENTITY を設定しました。次の採番値=%s",
                        TABLE_NAME,
                        COLUMN_NAME,
                        next_id,
                    )

        if dry_run:
            connection.rollback()
            logging.info("dry-runのため変更はコミットしませんでした")
        else:
            connection.commit()
            logging.info("IDENTITY設定をコミットしました")
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def verify_prerequisites(cursor: psycopg2.extensions.cursor, schema: str) -> None:
    if not table_exists(cursor, schema):
        raise ValueError(f"テーブルが存在しません: {qualified_name(schema, TABLE_NAME)}")

    if not has_primary_key_on_column(cursor, schema, COLUMN_NAME):
        raise ValueError(
            f"{TABLE_NAME}.{COLUMN_NAME} に PRIMARY KEY がありません。"
            "先に add_primary_keys_pingauge_management_db.py を実行してください。"
        )

    cursor.execute(
        f"SELECT COUNT(*) FROM {qualified_name(schema, TABLE_NAME)} WHERE {quote_identifier(COLUMN_NAME)} IS NULL"
    )
    null_count = int(cursor.fetchone()[0])
    if null_count > 0:
        raise ValueError(f"{TABLE_NAME}.{COLUMN_NAME} に NULL があります: {null_count}件")

    logging.info("前提条件の検証OK: %s.%s", TABLE_NAME, COLUMN_NAME)


def table_exists(cursor: psycopg2.extensions.cursor, schema: str) -> bool:
    cursor.execute(
        """
        SELECT COUNT(*)
        FROM information_schema.tables
        WHERE table_schema = %s AND table_name = %s
        """,
        (schema, TABLE_NAME),
    )
    return int(cursor.fetchone()[0]) > 0


def has_primary_key_on_column(cursor: psycopg2.extensions.cursor, schema: str, column_name: str) -> bool:
    cursor.execute(
        """
        SELECT COUNT(*)
        FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu
          ON tc.constraint_name = kcu.constraint_name
         AND tc.table_schema = kcu.table_schema
        WHERE tc.table_schema = %s
          AND tc.table_name = %s
          AND tc.constraint_type = 'PRIMARY KEY'
          AND kcu.column_name = %s
        """,
        (schema, TABLE_NAME, column_name),
    )
    return int(cursor.fetchone()[0]) > 0


def has_identity(cursor: psycopg2.extensions.cursor, schema: str) -> bool:
    cursor.execute(
        """
        SELECT is_identity
        FROM information_schema.columns
        WHERE table_schema = %s
          AND table_name = %s
          AND column_name = %s
        """,
        (schema, TABLE_NAME, COLUMN_NAME),
    )
    row = cursor.fetchone()
    return row is not None and row[0] == "YES"


def fetch_max_id(cursor: psycopg2.extensions.cursor, schema: str) -> int:
    cursor.execute(f"SELECT COALESCE(MAX({quote_identifier(COLUMN_NAME)}), 0) FROM {qualified_name(schema, TABLE_NAME)}")
    return int(cursor.fetchone()[0])


def fetch_identity_sequence(cursor: psycopg2.extensions.cursor, schema: str) -> str:
    cursor.execute(
        "SELECT pg_get_serial_sequence(%s, %s)",
        (f"{schema}.{TABLE_NAME}", COLUMN_NAME),
    )
    sequence_name = cursor.fetchone()[0]
    if not sequence_name:
        raise RuntimeError(f"{TABLE_NAME}.{COLUMN_NAME} のシーケンス名を取得できませんでした")
    return sequence_name


def sync_sequence(
    cursor: psycopg2.extensions.cursor,
    sequence_name: str,
    max_id: int,
    *,
    dry_run: bool,
) -> int:
    next_id = max_id + 1
    logging.info("シーケンス同期: %s -> 次の採番値 %s", sequence_name, next_id)
    if dry_run:
        return next_id

    cursor.execute("SELECT setval(%s, %s, %s)", (sequence_name, max_id, True))
    return next_id


def build_add_identity_sql(schema: str) -> str:
    table_name = qualified_name(schema, TABLE_NAME)
    column_name = quote_identifier(COLUMN_NAME)
    return (
        f"ALTER TABLE {table_name} "
        f"ALTER COLUMN {column_name} ADD GENERATED BY DEFAULT AS IDENTITY"
    )


def quote_identifier(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


def qualified_name(schema: str, table_name: str) -> str:
    return f"{quote_identifier(schema)}.{quote_identifier(table_name)}"


if __name__ == "__main__":
    raise SystemExit(main())
