"""セット予定材料管理DB の Access → PostgreSQL 英語名マッピング。"""

TABLE_NAME_MAP: dict[str, str] = {
    "t_コントロール": "app_control",
    "t_セット予定": "set_schedules",
    "t_チャックマスタ": "chuck_master",
    "t_一時停止": "production_pauses",
    "t_受信メールマスタ": "inbound_email_master",
    "t_営業担当マスタ": "sales_rep_master",
    "t_旧機械ID": "legacy_machine_ids",
    "t_材料管理": "material_orders",
    "t_材料納入履歴": "material_delivery_history",
    "t_材質": "material_types",
    "t_機械マスタ": "machine_master",
    "t_段取り者マスタ": "setup_operator_master",
    "t_汎用材料マスタ": "general_material_master",
    "t_汎用材料発注実績": "general_material_order_results",
    "t_注文書データ": "purchase_order_documents",
    "t_生産リリース": "production_releases",
    "t_生産リリース のコピー": "production_releases_backup",
    "t_生産発注": "production_orders",
    "t_発注者マスタ": "orderer_master",
    "t_管理表マスタ": "management_sheet_master",
    "t_納入業者": "suppliers",
    "t_送信メールマスタ": "outbound_email_master",
    "t_部品別チャックマスタ": "part_chuck_master",
}

COLUMN_NAME_MAP: dict[str, str] = {
    "ID": "id",
    "管理表更新日時": "management_sheet_updated_at",
    "セット予定表更新日時": "set_schedule_sheet_updated_at",
    "保存フォルダ": "save_folder",
    "セット予定日": "set_schedule_date",
    "機械NO": "machine_no",
    "シリアルNO": "serial_no",
    "品番": "part_no",
    "数量": "quantity",
    "必要最低数": "minimum_required_qty",
    "生産発注数": "production_order_qty",
    "材質材料径": "material_diameter",
    "材料使用本数": "material_bars_used",
    "前回秒数": "previous_cycle_seconds",
    "前回日産": "previous_daily_output",
    "加工予定日数": "planned_process_days",
    "加工終了日": "process_end_date",
    "管理No": "management_no",
    "管理NO": "management_no",
    "納期情報": "delivery_info",
    "セット者": "setup_operator",
    "備考": "remarks",
    "型": "model_type",
    "種別": "category",
    "サイズ": "size",
    "使用中": "in_use_count",
    "停止日": "pause_date",
    "納入業者コード": "supplier_code",
    "納入業者名": "supplier_name",
    "担当者To": "contact_to",
    "アドレスTo": "address_to",
    "担当者Cc": "contact_cc",
    "アドレスCc": "address_cc",
    "担当者名": "staff_name",
    "表示フラグ": "display_flag",
    "号機": "machine_unit",
    "機械ID": "machine_id",
    "製品名": "product_name",
    "客先名": "customer_name",
    "手配日": "arrangement_date",
    "納期": "delivery_date",
    "必要本数": "required_bars",
    "発注本数": "ordered_bars",
    "単位": "unit",
    "引当本数": "allocated_bars",
    "納入済数": "delivered_qty",
    "入荷残": "remaining_receipt_qty",
    "歩留": "yield_rate",
    "納期回答": "delivery_response_date",
    "発注先コード": "vendor_code",
    "発注先名": "vendor_name",
    "手配済フラグ": "arranged_flag",
    "注文書印刷済フラグ": "purchase_order_printed_flag",
    "材料入荷完了フラグ": "material_receipt_completed_flag",
    "入荷日": "receipt_date",
    "伝票日付": "slip_date",
    "区分": "category_code",
    "購入月": "purchase_month",
    "品種": "material_kind",
    "本数": "bar_count",
    "重量": "weight",
    "単価": "unit_price",
    "金額": "amount",
    "ロット番号": "lot_no",
    "入荷場所": "receipt_location",
    "材質": "material_type",
    "記号": "symbol",
    "機種": "machine_model",
    "仕様": "specification",
    "ソートキー": "sort_key",
    "段取り者": "setup_operator_name",
    "使用フラグ": "active_flag",
    "発注日": "order_date",
    "発注業者コード": "order_vendor_code",
    "材料テーブルID": "material_table_id",
    "材料名": "material_name",
    "セット日": "setup_date",
    "製品全長": "product_total_length",
    "突切り幅": "cutoff_width",
    "加工秒数": "process_seconds",
    "日産数": "daily_output_qty",
    "寸法出しH": "dimension_setup_h",
    "加工完了日": "process_completed_date",
    "完了フラグ": "completion_flag",
    "出力日": "export_date",
    "受注残数": "backorder_qty",
    "在庫": "stock_qty",
    "受注数": "order_qty",
    "注文数": "purchase_qty",
    "適正在庫": "optimal_stock_qty",
    "発注者": "orderer",
    "営業担当": "sales_rep",
    "Expフラグ": "exp_flag",
    "営業承認": "sales_approved",
    "Impフラグ": "imp_flag",
    "Imp日": "imp_date",
    "発注者名": "orderer_name",
    "製品番号": "product_code",
    "次工程": "next_process",
    "条件他": "other_conditions",
    "前回加工機": "previous_machine_no",
    "前回加工日": "previous_process_date",
    "取り数": "pieces_per_set",
    "在庫保管場所": "stock_location",
    "仕掛在庫": "wip_stock_qty",
    "指示書有無": "has_work_order",
    "材料識別": "material_identification",
    "締日": "closing_day",
    "計算方法": "calculation_method",
    "宛名": "addressee",
    "アドレス": "email_address",
    "パスワード": "password",
    "主担当フラグ": "primary_contact_flag",
}

IMPORTANT_COLUMN_NAMES = {
    "id",
    "product_code",
    "part_no",
    "machine_no",
    "serial_no",
    "management_no",
    "supplier_code",
    "order_date",
    "delivery_date",
    "setup_date",
}
