"""受注データDB の Access → PostgreSQL 英語名マッピング。"""

TABLE_NAME_MAP: dict[str, str] = {
    "imp管理表": "import_management_sheet",
    "t_かんばんマスタ": "kanban_master",
    "t_コントロール": "app_control",
    "t_プリンタ名": "printer_names",
    "t_受注": "orders",
    "t_営業マスタ": "sales_rep_master",
    "t_客先マスタ": "customer_master",
    "t_納品": "deliveries",
    "t_納品書": "delivery_notes",
    "t_納品書データ": "delivery_note_data",
    "t_製品マスタ": "product_master",
    "t_請求書": "invoices",
    "t_請求書Tmp": "invoices_temp",
    "t_請求金額": "billing_amounts",
    "t_請求金額決算": "billing_amounts_settlement",
    "t_重複客先": "duplicate_customers",
}

COLUMN_NAME_MAP: dict[str, str] = {
    "10月消費税額": "oct_consumption_tax",
    "10月請求額": "oct_billing_amount",
    "9月消費税額": "sep_consumption_tax",
    "9月請求額": "sep_billing_amount",
    "ID": "id",
    "ID1": "id1",
    "L/T": "lead_time",
    "NID": "delivery_id",
    "かな": "kana",
    "コード": "code",
    "セット予定日": "setup_planned_date",
    "フィールド15": "field_15",
    "フィールド16": "field_16",
    "フィールド17": "field_17",
    "フィールド18": "field_18",
    "フィールド19": "field_19",
    "フィールド20": "field_20",
    "フィールド22": "field_22",
    "フィールド24": "field_24",
    "フィールド30": "field_30",
    "フィールド31": "field_31",
    "フィールド32": "field_32",
    "フィールド34": "field_34",
    "プリンタ": "printer_name",
    "メモ": "memo",
    "不適合ロット数量": "nonconforming_lot_qty",
    "会社区分": "company_category",
    "備考": "remarks",
    "備考　、条件　等": "remarks_and_conditions",
    "備考　、条件　等　": "remarks_and_conditions_alt",
    "全長＋突切り幅": "total_length_with_cutoff",
    "出荷日": "ship_date",
    "別管理番号": "alt_management_no",
    "前回　　　加工秒数": "previous_machining_seconds",
    "前回加工": "previous_machining_at",
    "加工中": "in_process",
    "加工終了日": "machining_end_date",
    "加工費": "machining_cost",
    "単価": "unit_price",
    "取り数": "pickup_qty",
    "受注日": "order_date",
    "受注残数": "order_balance_qty",
    "品名": "product_name",
    "品名印刷": "product_name_print",
    "品番": "product_no",
    "営業": "sales_rep_short",
    "営業担当": "sales_rep",
    "在庫": "stock_qty",
    "在庫保管場所": "stock_storage_location",
    "在職フラグ": "active_flag",
    "売月": "sales_month",
    "完納フラグ": "completed_flag",
    "客先": "customer",
    "客先コード": "customer_code",
    "客先名": "customer_name",
    "客先正式": "customer_official_name",
    "当日完了ロット": "same_day_completed_lot",
    "担当": "person_in_charge",
    "指示書　有無": "instruction_sheet_flag",
    "摘要": "summary",
    "日産": "daily_output",
    "材料費": "material_cost",
    "材質&材料径": "material_and_diameter",
    "機械": "machine",
    "次工程": "next_process",
    "決算年": "settlement_year",
    "注文ID": "order_id",
    "注文ID年": "order_id_year",
    "注文ID連番": "order_id_seq",
    "注文数": "order_qty",
    "注文残": "order_balance",
    "注文番号": "order_no",
    "消費税計算": "consumption_tax_calc",
    "消費税額": "consumption_tax_amount",
    "生産予定数": "planned_production_qty",
    "突切": "cutoff",
    "納入日": "delivery_date",
    "納品数": "delivery_qty",
    "納品書客名": "delivery_note_customer_name",
    "納期": "due_date",
    "締日": "closing_day",
    "表示順": "display_order",
    "表面処理": "surface_treatment",
    "製品全長": "product_length",
    "製品名": "product_name",
    "製品番号": "product_no",
    "請求書印刷": "invoice_print",
    "請求月": "billing_month",
    "請求額": "billing_amount",
    "過不足数": "shortage_surplus_qty",
    "金額": "amount",
    "金額計算": "amount_calc",
}
