"""材料入庫管理台帳兼ミルシート管理表DB の Access → PostgreSQL 英語名マッピング。"""

TABLE_NAME_MAP: dict[str, str] = {
    "t_クロス集計用": "cross_aggregation",
    "t_コントロール": "app_control",
    "t_備考内容": "remarks_master",
    "t_旧検査データ": "legacy_inspection_data",
    "t_材料納入Tmp": "material_delivery_temp",
    "t_材料納入履歴": "material_delivery_history",
    "t_材料納入履歴 変更前": "material_delivery_history_before_change",
    "t_材質": "material_types",
    "t_検査データ": "inspection_data",
    "t_検査員": "inspectors",
    "t_納入業者": "suppliers",
}

COLUMN_NAME_MAP: dict[str, str] = {
    "ID": "id",
    "納入業者コード": "supplier_code",
    "納入業者名": "supplier_name",
    "購入月": "purchase_month",
    "金額": "amount",
    "書込みフォルダ": "write_folder",
    "購入月From": "purchase_month_from",
    "購入月To": "purchase_month_to",
    "コード": "code",
    "備考内容": "remark_text",
    "購入ID": "purchase_id",
    "寸法1": "dimension_1",
    "寸法2": "dimension_2",
    "判定結果": "judgment_result",
    "備考": "remarks",
    "検査員名": "inspector_name",
    "確認": "confirmed",
    "内容": "content",
    "入荷日": "receipt_date",
    "伝票日付": "slip_date",
    "区分": "category_code",
    "品種": "material_kind",
    "納入品目": "delivered_item",
    "サイズ": "size",
    "重量": "weight",
    "単価": "unit_price",
    "ロット番号": "lot_no",
    "使用製品番号": "used_product_no",
    "客先名": "customer_name",
    "仕様": "specification",
    "登録フラグ": "registered_flag",
    "入荷場所": "receipt_location",
    "材質": "material_type",
    "記号": "symbol",
    "締日": "closing_day",
    "計算方法": "calculation_method",
    "寸法1左最大": "dim1_left_max",
    "寸法1左最小": "dim1_left_min",
    "寸法1中最大": "dim1_center_max",
    "寸法1中最小": "dim1_center_min",
    "寸法1右最大": "dim1_right_max",
    "寸法1右最小": "dim1_right_min",
    "寸法2左最大": "dim2_left_max",
    "寸法2左最小": "dim2_left_min",
    "寸法2中最大": "dim2_center_max",
    "寸法2中最小": "dim2_center_min",
    "寸法2右最大": "dim2_right_max",
    "寸法2右最小": "dim2_right_min",
    "曲がり": "bending",
    "キズ": "scratch",
    "汚れ": "dirt",
}
