"""協力会社委託加工処理品DB の Access → PostgreSQL 英語名マッピング。"""

TABLE_NAME_MAP: dict[str, str] = {
    "t_クロス集計用": "cross_tab_summary",
    "t_コントロール": "app_control",
    "t_内職マスタ": "home_work_master",
    "t_客先": "customers",
    "t_手配先マスタ": "supplier_master",
    "t_発注": "purchase_orders",
    "t_発注 Start": "purchase_orders_start",
    "t_発注書": "purchase_order_forms",
    "t_発注書データ": "purchase_order_form_data",
    "t_納入": "deliveries",
    "t_納入 Start": "deliveries_start",
    "t_製品マスタ": "product_master",
}

COLUMN_NAME_MAP: dict[str, str] = {
    "ID": "id",
    "まとめコード": "summary_code",
    "手配先名": "supplier_name",
    "納入月": "delivery_month",
    "金額": "amount",
    "購入月From": "purchase_month_from",
    "購入月To": "purchase_month_to",
    "プリンタ": "printer_name",
    "品番": "product_no",
    "検査内容": "inspection_content",
    "検査治具": "inspection_jig",
    "単価": "unit_price",
    "コード": "code",
    "客先": "customer",
    "かな": "kana",
    "担当": "person_in_charge",
    "手配先コード": "supplier_code",
    "発注区分": "order_category",
    "集計フラグ": "aggregation_flag",
    "計算方法": "calculation_method",
    "表示フラグ": "display_flag",
    "発注ID": "purchase_order_id",
    "発注日": "order_date",
    "注文番号": "order_no",
    "品名": "product_name",
    "客先名": "customer_name",
    "表面処理": "surface_treatment",
    "納期": "due_date",
    "発注数": "order_qty",
    "納入済数": "delivered_qty",
    "納入残": "delivery_balance",
    "備考": "remarks",
    "加工日": "processing_date",
    "機番": "machine_no",
    "完了フラグ": "completed_flag",
    "摘要": "summary",
    "会社区分": "company_category",
    "納期担当": "due_date_person",
    "納入ID": "delivery_id",
    "納入日": "delivery_date",
    "納入数": "delivery_qty",
    "製品番号": "product_code",
    "製品名": "product_name_full",
    "次工程": "next_process",
    "外部委託加工費": "external_subcontract_cost",
}
